# Generated by Django 5.2.3 on 2025-06-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
